version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

      - image: mysql:5.7.21
        environment:
          MYSQL_ROOT_PASSWORD=password

      - image: postgres:9.4
        environment:
          POSTGRES_PASSWORD=password

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test
